export default {
    MAX_PLAYERS_PER_ROOM: 8,
    MIN_PLAYERS_PER_ROOM: 4,
    ROUND_DELAY: 5 * 1000,
    MAX_ROUND_POINTS: 500,
    ROUND_POINT_THRESHOLD: 251,
    MAX_BASE_SCORE: 200,
    MAX_HINT_BONUS_SCORE: 60
};